spring.application.name=aiservice

server.port = 8082
eureka.client.service-url.defaultZone = http://localhost:8761/eureka/

#spring.mongodb.host=localhost
#spring.mongodb.port=27017
#spring.mongodb.database=fitnessrecommendation

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=fitnessrecommendation

#kafka connection as Consumer details
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer



#creating a topic
my.topic.name=activity-topic

#Assigning the consumer a groupID
spring.kafka.consumer.group-id="SBMS"

# Gemini API Key
gemini.api.key=AIzaSyBrFdM4ePkXQrAJcbSF-M7nPWA4eoSDMsM

# Gemini Base URL (optional but useful)
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
